[tool.poetry]
name = "fastapi"
version = "0.1.0"
description = ""
authors = ["Ish Kumar <ish1301@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.86.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
